<?php
/**
 * create.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\CreateView $viewModel */
$viewModel = $block->getViewModel();

/** @var Magento\Sales\Api\Data\OrderInterface $order */
$order = $viewModel->getOrder();

/** @var array $reasons */
$reasons = $viewModel->getReasons();

/** @var array $resolutions */
$resolutions = $viewModel->getResolutions();
?>
<div class="block simplereturns-rma-create">
    <div class="simplereturns-rma-form">
        <div class="container-form">
            <form method="POST" action="<?= $block->escapeUrl($viewModel->getPostActionUrl()) ?>" id="simplereturns-rma-create-form">
                <?= $block->getBlockHtml('formkey') ?>
                <fieldset class="fieldset simplereturns" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                    <legend class="legend">
                        <span><?= $block->escapeHtml(__('Create Return for Order #%1', $order->getRealOrderId())) ?></span>
                    </legend>
                    <div class="field order_id required">
                        <label class="label order_id" for="order_id">
                            <span><?= $block->escapeHtml(__('Order ID')) ?></span>
                        </label>
                        <div class="control">
                            <input name="simplereturns[order_id]"
                                   id="order_id"
                                   type="text"
                                   class="form-input input-text"
                                   value="<?= $block->escapeHtmlAttr($order->getRealOrderId()) ?>"
                                   readonly
                                   title="<?= $block->escapeHtmlAttr(__('Order ID')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'>
                        </div>
                    </div>
                    <div class="field protect_code required">
                        <div class="control">
                            <input name="simplereturns[protect_code]"
                                   id="protect_code"
                                   type="hidden"
                                   class="form-input input-text"
                                   value="<?= $block->escapeHtmlAttr($order->getProtectCode()) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'>
                        </div>
                    </div>
                    <div class="field reason required">
                        <label class="label reason" for="reason">
                            <span><?= $block->escapeHtml(__('Reason')) ?></span>
                        </label>
                        <div class="control">
                            <select id="reason" name="simplereturns[reason]" class="select">
                                <?php foreach ($reasons as $value => $label): ?>
                                    <option value="<?= $block->escapeHtmlAttr(__($value)) ?>"><?= $block->escapeHtml(__($label)) ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="field resolution required">
                        <label class="label resolution" for="resolution">
                            <span><?= $block->escapeHtml(__('Resolution')) ?></span>
                        </label>
                        <div class="control">
                            <select id="resolution" name="simplereturns[resolution]" class="select">
                                <?php foreach ($resolutions as $value => $label): ?>
                                    <option value="<?= $block->escapeHtmlAttr(__($value)) ?>"><?= $block->escapeHtml(__($label)) ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                    <div class="field comments optional">
                        <label class="label comments" for="comments">
                            <span><?= $block->escapeHtml(__('Comments')) ?></span>
                        </label>
                        <div class="control">
                            <textarea id="comments" name="simplereturns[comments]"></textarea>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" type="submit">
                            <span><?= $block->escapeHtml(__('Submit')) ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
