<?php
/**
 * create.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\CreateView $viewModel */
$viewModel = $block->getViewModel();

/** @var Magento\Sales\Api\Data\OrderInterface $order */
$order = $viewModel->getOrder();

/** @var array $reasons */
$reasons = $viewModel->getReasons();
?>
<div class="block returns-rma-create">
    <div class="returns-rma-form">
        <div class="container-form">
            <form method="POST" action="<?= $block->escapeUrl($viewModel->getPostActionUrl()) ?>" id="returns-rma-form">
                <?= $block->getBlockHtml('formkey') ?>
                <fieldset class="fieldset returns" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                    <legend class="legend">
                        <span><?= $block->escapeHtml(__('New Return for Order #%1', $order->getRealOrderId())) ?></span>
                    </legend>
                    <div class="field order_id required">
                        <label class="label order_id" for="order_id">
                            <span><?= $block->escapeHtml(__('Order ID')) ?></span>
                        </label>
                        <div class="control">
                            <input name="returns[order_id]"
                                   id="order_id"
                                   type="text"
                                   class="form-input input-text"
                                   value="<?= $block->escapeHtmlAttr($order->getRealOrderId()) ?>"
                                   disabled
                                   title="<?= $block->escapeHtmlAttr(__('Order ID')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'>
                        </div>
                    </div>
                    <div class="field reason required">
                        <label class="label reason" for="reason">
                            <span><?= $block->escapeHtml(__('Reason')) ?></span>
                        </label>
                        <div class="control">
                            <select class="select">
                                <?php foreach ($reasons as $reason): ?>
                                    <option value="<?= $reason ?>"><?= $reason ?></option>
                                <?php endforeach ?>
                            </select>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
