<?php
/**
 * view.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var AuroraExtensions\SimpleReturns\Api\Data\SimpleReturnInterface */
$rma = $viewModel->getSimpleReturn();
?>
<div class="block simplereturns-rma-view">
    <h3><?= $block->escapeHtml(__('View Return for Order #%1', $rma->getOrderId())) ?></h3>
    <div class="container">
        <div class="simplereturns-rma-id"><?= $block->escapeHtml(__('Return #: #%1', $rma->getId())) ?></div>
        <div class="simplereturns-rma-reason"><?= $block->escapeHtml(__('Reason: %1', $rma->getReason())) ?></div>
        <div class="simplereturns-rma-resolution"><?= $block->escapeHtml(__('Resolution: %1', $rma->getResolution())) ?></div>
        <div class="simplereturns-rma-comments"><?= $block->escapeHtml(__('Comments: %1', $rma->getComments())) ?></div>
    </div>
</div>
