<?php
/**
 * view.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/**
 * @use AuroraExtensions\SimpleReturns\Api\Data\LabelInterface
 * @use AuroraExtensions\SimpleReturns\Api\Data\PackageInterface
 * @use AuroraExtensions\SimpleReturns\Api\Data\SimpleReturnInterface
 * @use AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\ViewView
 * @use Magento\Framework\View\Element\Template
 * @use Magento\Sales\Api\Data\OrderInterface
 */

/** @var Template $block */
/** @var ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var SimpleReturnInterface $rma */
$rma = $viewModel->getSimpleReturn();

/** @var OrderInterface $order */
$order = $viewModel->getOrder();

/** @var array $attachments */
$attachments = $viewModel->getAttachments();

/** @var bool $hasPackage */
$hasPackage = $viewModel->hasPackage();
?>
<div class="block simplereturns">
    <h2><?= $block->escapeHtml(__('View RMA Details for Order #%1', $order->getRealOrderId())) ?></h2>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Actions')) ?></h3>
    <div class="actions">
        <a class="action" href="<?= $viewModel->getEditRmaUrl() ?>"><?= $block->escapeHtml(__('Edit RMA Details')) ?></a>
        <?php if ($hasPackage): ?>
        <a class="action" href="<?= $viewModel->getViewPackageUrl() ?>"><?= $block->escapeHtml(__('View Package Details')) ?></a>
        <?php else: ?>
        <a class="action" href="<?= $viewModel->getCreatePackageUrl() ?>"><?= $block->escapeHtml(__('Create Package')) ?></a>
        <?php endif ?>
    </div>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Details')) ?></h3>
    <div class="details">
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Return')) ?></span>
            <span class="value">
                <?= $block->escapeHtml(
                    __(
                        '#%1',
                        $rma->getFrontId()
                    )
                ) ?>
            </span>
        </div>
        <?php if ($hasPackage): ?>
        <?php /** @var PackageInterface $package */ ?>
        <?php $package = $viewModel->getPackage() ?>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Package')) ?></span>
            <span class="value">
                <?= $block->escapeHtml(
                    __(
                        '#%1',
                        $package->getFrontId()
                    )
                ) ?>
            </span>
        </div>
        <?php endif ?>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Order')) ?></span>
            <span class="value">
                <?= $block->escapeHtml(
                    __(
                        '#%1',
                        $order->getRealOrderId()
                    )
                ) ?>
            </span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Status')) ?></span>
            <span class="value">
                <?= $block->escapeHtml(
                    __(
                        '%1',
                        $viewModel->getFrontLabel('statuses', $rma->getStatus())
                    )
                ) ?>
            </span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Reason')) ?></span>
            <span class="value">
                <?= $block->escapeHtml(
                    __(
                        '%1',
                        $viewModel->getFrontLabel('reasons', $rma->getReason())
                    )
                ) ?>
            </span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Resolution')) ?></span>
            <span class="value">
                <?= $block->escapeHtml(
                    __(
                        '%1',
                        $viewModel->getFrontLabel('resolutions', $rma->getResolution())
                    )
                ) ?>
            </span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Comments')) ?></span>
            <span class="value"><?= $block->escapeHtml($rma->getComments()) ?></span>
        </div>
        <?php if ($viewModel->hasAttachments()): ?>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Attachments')) ?></span>
            <span class="value attachments">
            <?php foreach ($attachments as $attachment): ?>
                <div class="attachment">
                    <a href="<?= $block->escapeUrl($attachment) ?>" target="_blank">
                        <img src="<?= $block->escapeUrl($attachment) ?>"/>
                    </a>
                </div>
            <?php endforeach ?>
            </span>
        </div>
        <?php endif ?>
    </div>
</div>
