<?php
/**
 * view.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var AuroraExtensions\SimpleReturns\Api\Data\SimpleReturnInterface $rma */
$rma = $viewModel->getSimpleReturn();

/** @var Magento\Sales\Api\Data\OrderInterface $order */
$order = $viewModel->getOrder();
?>
<div class="block simplereturns-rma-view">
    <h2><?= $block->escapeHtml(__('View Return for Order #%1', $order->getRealOrderId())) ?></h2>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Actions')) ?></h3>
    <div class="actions">
        <a href="<?= $viewModel->getCreatePackageUrl() ?>" target="_blank"><?= $block->escapeHtml(__('Create Return Shipment')) ?></a>
        <a href="<?= $viewModel->getViewLabelUrl() ?>" target="_blank"><?= $block->escapeHtml(__('Print Label')) ?></a>
    </div>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Details')) ?></h3>
    <div class="details">
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Order')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('#%1', $order->getRealOrderId())) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Status')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('%1', $viewModel->getFrontendLabel('statuses', $rma->getStatus()))) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Reason')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('%1', $viewModel->getFrontendLabel('reasons', $rma->getReason()))) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Resolution')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('%1', $viewModel->getFrontendLabel('resolutions', $rma->getResolution()))) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Comments')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('%1', $rma->getComments())) ?></span>
        </div>
    </div>
</div>
