<?php
/**
 * index.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/returns/LICENSE.txt
 *
 * @package       AuroraExtensions_Returns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\Returns\ViewModel\Label $viewModel */
$viewModel = $block->getViewModel();

/** @var bool $hasLabel */
$hasLabel = $viewModel->hasLabel();
?>
<div class="page-returns-label">
    <div class="page-title">
        <h1 class="return-label-title"><?php echo $block->escapeHtml(__('Return Label')) ?></h1>
    </div>
    <div class="returns-label-content">
        <div class="content-buttons">
            <?php if ($hasLabel): ?>
                <button class="button print" title="Print Label" type="button" data-mage-init='{"printLabel":{}}'><?php echo $block->escapeHtml(__('Print Label')) ?></button>
            <?php endif ?>
        </div>
        <div class="content-label">
            <?php if ($hasLabel): ?>
                <img alt="Return Label" class="return-label" src="<?php echo $viewModel->getLabelEncodedDataUri() ?>"/>
                <img alt="Return Form" class="return-form" src="<?php echo $viewModel->getReturnFormUrl() ?>"/>
            <?php else: ?>
                <div class="error validation-error shipping-label-message"><?php echo $block->escapeHtml(__('We were unable to generate a label for this order.')) ?></div>
                <ul class="error-reasons">
                    <?php foreach ($viewModel->getErrorMessages() as $message): ?>
                        <li><?php echo $message ?></li>
                    <?php endforeach ?>
                </ul>
            <?php endif ?>
        </div>
    </div>
</div>
