<?php
/**
 * orders.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\OrdersView $viewModel */
$viewModel = $block->getViewModel();

/** @var string $email The email address, as provided by user. */
/** @var string $orderId The order ID, as provided by user. */
/** @var string $zipCode The zip code, as provided by user. */
$email = $viewModel->getEmail();
$orderId = $viewModel->getOrderId();
$zipCode = $viewModel->getZipCode();
?>
<div class="block page-returns">
    <div class="block-title page-title">
        <h1><?= $block->escapeHtml(__('Print Return Label')) ?></h1>
    </div>

    <?php if (!$viewModel->getIsChecked()): ?>
        <div class="returns-form">
            <div class="container-form">
                <form method="POST" action="<?= $block->escapeUrl($viewModel->getPostActionUrl()) ?>" id="returns-label-form">
                    <?= $block->getBlockHtml('formkey') ?>
                    <fieldset class="fieldset returns" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                        <div class="field zip_code required">
                            <label class="label zip_code" for="zip_code"><span><?= $block->escapeHtml(__('Billing or Shipping Zip Code')) ?></span></label>
                            <input name="returns[zip_code]"
                                   value="<?= $block->escapeHtmlAttr($zipCode) ?>"
                                   id="zip_code"
                                   type="text"
                                   class="form-input input-text"
                                   title="<?= $block->escapeHtmlAttr(__('Billing or Shipping Zip Code')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'>
                        </div>
                        <div class="field note">
                            <span>AND</span>
                        </div>
                        <div class="field email required">
                            <label class="label email" for="email">
                                <span><?= $block->escapeHtml(__('Email Address')) ?></span>
                            </label>
                            <input name="returns[email]"
                                   value="<?= $block->escapeHtmlAttr($email) ?>"
                                   id="email"
                                   type="email"
                                   class="form-input input-text"
                                   title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{'validate-email':true}">
                        </div>
                        <div class="field note"><span>OR</span></div>
                        <div class="field order_id required">
                            <label class="label order_id" for="order_id">
                                <span><?= $block->escapeHtml(__('Order ID')) ?></span>
                            </label>
                            <input name="returns[order_id]"
                                   value="<?= $block->escapeHtmlAttr($orderId) ?>"
                                   id="order_id"
                                   type="text"
                                   class="form-input input-text"
                                   title="<?= $block->escapeHtmlAttr(__('Order ID')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" class="action print-returns-label primary" name="send" id="send2">
                                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    <?php else: ?>
        <div class="returns-orders">
            <?php if ($viewModel->hasOrders()): ?>
                <div class="orders-table">
                    <div class="orders-header">
                        <?php foreach ($block->getColumnHeaders() as $key => $value): ?>
                            <li name="<?= $block->escapeHtmlAttr(__($key)) ?>"><?= $block->escapeHtml(__($value)) ?></li>
                        <?php endforeach ?>
                    </div>
                    <div class="orders-body">
                        <?php foreach ($viewModel->getOrders() as $order): ?>
                            <ul>
                                <li><?= $block->escapeHtml($order->getRealOrderId()) ?></li>
                                <li><?= $block->escapeHtml($order->getCreatedAt()) ?></li>
                                <li><?= $block->escapeHtml($order->getGrandTotal()) ?></li>
                                <li><em><?= $block->escapeHtml($order->getStatusLabel()) ?></em></li>
                                <?php if ($viewModel->isOrderPrepaidEligible($order)): ?>
                                    <li>
                                        <a href="<?= $block->escapeHtmlAttr($viewModel->getReturnLabelUrl($order)) ?>" target="_blank"><?= $block->escapeHtml(__('Print Return Label')) ?></a>
                                    </li>
                                <?php endif ?>
                            </ul>
                        <?php endforeach ?>
                    </div>
                </div>
            <?php else: ?>
                <?php /** @var string $searchMethod */ ?>
                <?php $searchMethod = $email !== null ? 'email address and zip code' : 'order ID and zip code' ?>
                <p><?= $block->escapeHtml(__('Sorry, no orders were found for the specified ' . $searchMethod . '.')) ?></p>
                <button type="button" title="Go Back" class="button back" onclick="window.history.back();">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </button>
            <?php endif ?>
        </div>
    <?php endif ?>
</div>
