<?php
/**
 * create.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\Package\CreateView $viewModel */
$viewModel = $block->getViewModel();

/** @var AuroraExtensions\SimpleReturns\Api\Data\SimpleReturnInterface $rma */
$rma = $viewModel->getSimpleReturn();

/** @var Magento\Sales\Api\Data\OrderInterface $order */
$order = $viewModel->getOrder();

/** @var float $packageWeight */
$packageWeight = $viewModel->getPackageWeight();

/** @var string $weightUnits */
$weightUnits = $viewModel->getWeightUnits();
?>
<div class="block simplereturns-package-create">
    <h2><?= $block->escapeHtml(__('Create Return Package for Order #%1', $order->getRealOrderId())) ?></h2>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Details')) ?></h3>
    <div class="details">
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Order')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('#%1', $order->getRealOrderId())) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Package Weight')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('%1 (%2)', $packageWeight, $weightUnits)) ?></span>
        </div>
    </div>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Actions')) ?></h3>
    <div class="simplereturns-package-create-form">
        <div class="container-form">
            <form method="POST" action="<?= $block->escapeUrl($viewModel->getPostActionUrl()) ?>" id="simplereturns-package-create-form">
                <?= $block->getBlockHtml('formkey') ?>
                <fieldset class="fieldset simplereturns_package" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                    <div class="field generate_shipping_label required">
                        <label class="label generate_shipping_label" for="generate_shipping_label">
                            <span><?= $block->escapeHtml(__('Generate Shipping Label')) ?></span>
                        </label>
                        <div class="control">
                            <select id="generate_shipping_label" name="simplereturns_package[generate_shipping_label]" class="select">
                                <option value="yes"><?= $block->escapeHtml(__('Yes')) ?></option>
                                <option value="no"><?= $block->escapeHtml(__('No')) ?></option>
                            </select>
                        </div>
                    </div>
                </fieldset>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button class="action submit" title="<?= $block->escapeHtmlAttr(__('Confirm')) ?>" type="submit">
                            <span><?= $block->escapeHtml(__('Confirm')) ?></span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
