<?php
/**
 * view.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\Package\ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var AuroraExtensions\SimpleReturns\Api\Data\PackageInterface $package */
$package = $viewModel->getPackage();

/** @var AuroraExtensions\SimpleReturns\Api\Data\SimpleReturnInterface $rma */
$rma = $viewModel->getSimpleReturn();
?>
<div class="block simplereturns-package-view">
</div>
