<?php
/**
 * view.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\Label\ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var bool $hasLabel */
$hasLabel = $viewModel->hasLabel();
?>
<div class="simplereturns-label-view">
    <div class="page-title">
        <h1 class="simplereturns-label-title"><?= $block->escapeHtml(__('Return Label')) ?></h1>
    </div>
    <div class="simplereturns-label-content">
        <div class="label-content-buttons">
            <?php if ($hasLabel): ?>
                <button class="button print" title="Print Label" type="button" data-mage-init='{"labelPrint":{}}'><?= $block->escapeHtml(__('Print Label')) ?></button>
            <?php endif ?>
        </div>
        <div class="label-content-image">
            <?php if ($hasLabel): ?>
                <img alt="Return Label" class="return-label" src="<?= $viewModel->getLabelDataUri() ?>"/>
            <?php else: ?>
                <div class="error validation-error shipping-label-message"><?= $block->escapeHtml(__('There was an issue trying to generate a return label for this order.')) ?></div>
            <?php endif ?>
        </div>
    </div>
</div>
