<?php
/**
 * view.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/**
 * @use AuroraExtensions\SimpleReturns\Api\Data\LabelInterface
 * @use AuroraExtensions\SimpleReturns\Api\Data\PackageInterface
 * @use AuroraExtensions\SimpleReturns\Api\Data\SimpleReturnInterface
 * @use AuroraExtensions\SimpleReturns\Model\ViewModel\Label\ViewView
 * @use Magento\Framework\View\Element\Template
 * @use Magento\Sales\Api\Data\OrderInterface
 */

/** @var Template $block */
/** @var ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var SimpleReturnInterface $rma */
$rma = $viewModel->getSimpleReturn();

/** @var PackageInterface $package */
$package = $viewModel->getPackage();

/** @var LabelInterface $label */
$label = $viewModel->getLabel();

/** @var OrderInterface $order */
$order = $viewModel->getOrder();
?>
<div class="block simplereturns simplereturns-label-view">
    <div class="page-title">
        <h2 class="simplereturns-label-title"><?= $block->escapeHtml(__('View RMA Package Shipping Label for Order #%1', $order->getRealOrderId())) ?></h2>
    </div>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Actions')) ?></h3>
    <div class="actions">
        <a class="action" href="<?= $viewModel->getViewRmaUrl() ?>"><?= $block->escapeHtml(__('View RMA Details')) ?></a>
        <a class="action" href="#" title="Print" data-mage-init='{"labelPrint":{}}'><?= $block->escapeHtml(__('Print Label')) ?></a>
    </div>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Details')) ?></h3>
    <div class="details">
        <div class="info">
            <div class="row">
                <span class="title"><?= $block->escapeHtml(__('Label')) ?></span>
                <span class="value"><?= $block->escapeHtml(__('#%1', $label->getFrontId())) ?></span>
            </div>
            <div class="row">
                <span class="title"><?= $block->escapeHtml(__('Return')) ?></span>
                <span class="value"><?= $block->escapeHtml(__('#%1', $rma->getFrontId())) ?></span>
            </div>
            <div class="row">
                <span class="title"><?= $block->escapeHtml(__('Package')) ?></span>
                <span class="value"><?= $block->escapeHtml(__('#%1', $package->getFrontId())) ?></span>
            </div>
            <div class="row">
                <span class="title"><?= $block->escapeHtml(__('Order')) ?></span>
                <span class="value"><?= $block->escapeHtml(__('#%1', $order->getRealOrderId())) ?></span>
            </div>
        </div>
        <div class="thumbnail">
            <img alt="Shipping Label" src="<?= $viewModel->getLabelDataUri() ?>"/>
        </div>
    </div>
</div>
