<?php
/**
 * view.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\Label\ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var AuroraExtensions\SimpleReturns\Api\Data\SimpleReturnInterface $rma */
$rma = $viewModel->getSimpleReturn();

/** @var AuroraExtensions\SimpleReturns\Api\Data\PackageInterface $package */
$package = $viewModel->getPackage();

/** @var bool $hasLabel */
$hasLabel = $viewModel->hasLabel();

/** @var Magento\Sales\Api\Data\OrderInterface $order */
$order = $viewModel->getOrder();
?>
<div class="simplereturns-label-view">
    <div class="page-title">
        <h2 class="simplereturns-label-title"><?= $block->escapeHtml(__('View RMA Package Shipping Label for Order #%1', $order->getRealOrderId())) ?></h2>
    </div>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Actions')) ?></h3>
    <div class="actions">
        <a class="action" href="<?= $viewModel->getViewRmaUrl() ?>"><?= $block->escapeHtml(__('View RMA Details')) ?></a>
        <a class="action" href="#" title="Print" data-mage-init='{"labelPrint":{}}'><?= $block->escapeHtml(__('Print Label')) ?></a>
    </div>
    <h3 class="subtitle"><?= $block->escapeHtml(__('Details')) ?></h3>
    <div class="details">
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Return')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('#%1', $rma->getFrontId())) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Package')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('#%1', $package->getFrontId())) ?></span>
        </div>
        <div class="row">
            <span class="title"><?= $block->escapeHtml(__('Order')) ?></span>
            <span class="value"><?= $block->escapeHtml(__('#%1', $order->getRealOrderId())) ?></span>
        </div>
        <div class="row">
            <span class="value thumbnail">
                <img alt="Shipping Label" src="<?= $viewModel->getLabelDataUri() ?>"/>
            </span>
        </div>
    </div>
</div>
