<?php
/**
 * search.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT license, which
 * is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package     AuroraExtensions\SimpleReturns
 * @copyright   Copyright (C) 2023 Aurora Extensions <support@auroraextensions.com>
 * @license     MIT
 */

/** @var Magento\Framework\View\Element\Template $block */
/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\Orders\SearchView $viewModel */
$viewModel = $block->getViewModel();
?>
<div class="block simplereturns-orders-search">
    <div class="simplereturns-orders-search-form">
        <div class="container-form">
            <form method="POST" action="<?= $block->escapeUrl($viewModel->getPostActionUrl()) ?>" id="simplereturns-orders-search-form">
                <?= $block->getBlockHtml('formkey') ?>
                <fieldset class="fieldset simplereturns" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                    <legend class="legend">
                        <span><?= $block->escapeHtml(__('Please enter the Zip Code for the order')); ?></span>
                    </legend>
                    <div class="field zip_code required">
                        <label class="label zip_code" for="zip_code">
                            <span><?= $block->escapeHtml(__('Billing or Shipping Zip Code')) ?></span>
                        </label>
                        <div class="control">
                            <input name="simplereturns[zip_code]"
                                   id="zip_code"
                                   type="text"
                                   class="form-input input-text"
                                   title="<?= $block->escapeHtmlAttr(__('Billing or Shipping Zip Code')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'>
                        </div>
                    </div>
                </fieldset>
                <fieldset class="fieldset simplereturns" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                    <legend class="legend">
                        <span><?= $block->escapeHtml(__('Please enter the Email Address for the order or the Order ID')); ?></span>
                    </legend>
                    <div class="field email required">
                        <label class="label email" for="email">
                            <span><?= $block->escapeHtml(__('Email Address')) ?></span>
                        </label>
                        <div class="control">
                            <input name="simplereturns[email]"
                                   id="email"
                                   type="email"
                                   class="form-input input-text"
                                   title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'
                                   data-validate="{'validate-email':true}">
                        </div>
                    </div>
                    <div class="field order_id required">
                        <label class="label order_id" for="order_id">
                            <span><?= $block->escapeHtml(__('Order ID')) ?></span>
                        </label>
                        <div class="control">
                            <input name="simplereturns[order_id]"
                                   id="order_id"
                                   type="text"
                                   class="form-input input-text"
                                   title="<?= $block->escapeHtmlAttr(__('Order ID')) ?>"
                                   data-mage-init='{"mage/trim-input":{}}'>
                        </div>
                    </div>
                    <div class="actions-toolbar">
                        <div class="primary">
                            <button type="submit" class="action primary" name="send" id="send3">
                                <span><?= $block->escapeHtml(__('Submit')) ?></span>
                            </button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
