<?php
/**
 * buttons.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License, which
 * is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       MIT License
 */

/**
 * @use AuroraExtensions\SimpleReturns\Model\ViewModel\Sales\Order\Info\ActionsView
 * @use Magento\Sales\Api\Data\OrderInterface
 * @use Magento\Sales\Block\Order\Info\Buttons
 */

/**
 * @see Magento_Sales::order/info/buttons.phtml
 * @var Buttons $block
 */
use Magento\Framework\Data\Helper\PostHelper;
use Magento\Sales\Helper\Reorder as ReorderHelper;

/** @var ActionsView $viewModel */
$viewModel = $block->getViewModel();

/** @var OrderInterface $order */
$order = $block->getOrder();
?>
<div class="actions">
    <?php if ($this->helper(ReorderHelper::class)->canReorder($order->getEntityId())) : ?>
        <a href="#" data-post='<?=
        /* @noEscape */ $this->helper(PostHelper::class)
            ->getPostData($block->getReorderUrl($order))
        ?>' class="action order">
            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
        </a>
    <?php endif ?>
    <?php if ($viewModel->hasSimpleReturn($order)): ?>
        <a class="action view-rma" href="<?= $block->escapeUrl($viewModel->getRmaViewUrl($order)) ?>">
            <span><?= $block->escapeHtml(__('View Return')) ?></span>
        </a>
    <?php else: ?>
        <a class="action create-rma" href="<?= $block->escapeUrl($viewModel->getRmaCreateUrl($order)) ?>">
            <span><?= $block->escapeHtml(__('Return or replace items')) ?></span>
        </a>
    <?php endif ?>
    <a class="action print"
       href="<?= $block->escapeUrl($block->getPrintUrl($order)) ?>"
       onclick="this.target='_blank';">
        <span><?= $block->escapeHtml(__('Print Order')) ?></span>
    </a>
    <?= $block->getChildHtml() ?>
</div>
