<?php
/**
 * comments.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/**
 * @use AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\EditView
 * @use Magento\Framework\View\Element\Template
 */

/** @var Template $block */
/** @var EditView $viewModel */
$viewModel = $block->getViewModel();

/** @var SimpleReturnInterface $rma */
$rma = $viewModel->getSimpleReturn();
?>
<blockquote id="simplereturns-rma-comments">
    <span><?= $block->escapeHtml(__('%1', $rma->getComments())) ?></span>
</blockquote>
