<?php
/**
 * order_link.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License, which
 * is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       MIT License
 */

/** @var Template $block */
/** @var CreateView $viewModel */
$viewModel = $block->getViewModel();

/** @var OrderInterface $order */
$order = $viewModel->getOrder();

/** @var string $orderId */
$orderId = $order->getRealOrderId();
?>
<a class="simplereturns-order-link" href="#"><?= $block->escapeHtml(__('Order #%1', $orderId)) ?></a>
