<?php
/**
 * order_link.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT license, which
 * is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package     AuroraExtensions\SimpleReturns
 * @copyright   Copyright (C) 2023 Aurora Extensions <support@auroraextensions.com>
 * @license     MIT
 */

/** @var Template $block */
/** @var CreateView $viewModel */
$viewModel = $block->getViewModel();

/** @var OrderInterface $order */
$order = $viewModel->getOrder();

/** @var string $orderId */
$orderId = $order->getRealOrderId();

/** @var string $orderUrl */
$orderUrl = $viewModel->getViewOrderUrl() ?? '#';
?>
<div class="simplereturns__container">
    <div class="simplereturns__field">
        <div class="simplereturns__field-label">
            <span><?= $block->escapeHtml(__('Order')) ?></span>
        </div>
        <div class="simplereturns__field-control">
            <a class="simplereturns-order-link" href="<?= $block->escapeUrl($orderUrl) ?>"><?= $block->escapeHtml(__('#%1', $orderId)) ?></a>
        </div>
    </div>
</div>
