<?php
/**
 * view.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/**
 * @use AuroraExtensions\SimpleReturns\Api\Data\LabelInterface
 * @use AuroraExtensions\SimpleReturns\Api\Data\PackageInterface
 * @use AuroraExtensions\SimpleReturns\Api\Data\SimpleReturnInterface
 * @use AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\ViewView
 * @use Magento\Framework\View\Element\Template
 * @use Magento\Sales\Api\Data\OrderInterface
 */

/** @var Template $block */
/** @var ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var SimpleReturnInterface $rma */
$rma = $viewModel->getSimpleReturn();

/** @var OrderInterface $order */
$order = $viewModel->getOrder();

/** @var array $attachments */
$attachments = $viewModel->getAttachments();

/** @var bool $hasMedia */
$hasMedia = $viewModel->hasAttachments();

/** @var bool $hasPackage */
$hasPackage = $viewModel->hasPackage();

/** @var string $customerUrl */
$customerUrl = $viewModel->getViewCustomerUrl();
?>
<section class="admin__page-section simplereturns-rma-info">
    <div class="admin__page-section-title">
        <span class="title"><?= $block->escapeHtml(__('View RMA Details for Order #%1', $order->getRealOrderId())) ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item rma-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary rma-information-table">
                    <tr>
                        <th><?= $block->escapeHtml(__('Created')) ?></th>
                        <td><?= $block->escapeHtml($rma->getCreatedAt()) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Updated')) ?></th>
                        <td><?= $block->escapeHtml($rma->getUpdatedAt()) ?></td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Status')) ?></th>
                        <td>
                            <span id="rma_status">
                                <?= $block->escapeHtml(
                                    __(
                                        '%1',
                                        $viewModel->getFrontLabel('statuses', $rma->getStatus())
                                    )
                                ) ?>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Reason')) ?></th>
                        <td>
                            <span id="rma_reason">
                                <?= $block->escapeHtml(
                                    __(
                                        '%1',
                                        $viewModel->getFrontLabel('reasons', $rma->getReason())
                                    )
                                ) ?>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Resolution')) ?></th>
                        <td>
                            <span id="rma_resolution">
                                <?= $block->escapeHtml(
                                    __(
                                        '%1',
                                        $viewModel->getFrontLabel('resolutions', $rma->getResolution())
                                    )
                                ) ?>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <th><?= $block->escapeHtml(__('Comments')) ?></th>
                        <td>
                            <span id="rma_comments"><?= $block->escapeHtml(__('%1', $rma->getComments())) ?></span>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</section>
<?php if ($hasMedia): ?>
<section class="admin__page-section simplereturns-rma-attachments">
    <div class="admin__page-section-item">
        <div class="admin__page-section-item-title">
            <span class="title"><?= $block->escapeHtml(__('Attachments')) ?></span>
        </div>
        <div class="admin__page-section-item-content">
            <?php foreach ($attachments as $attachment): ?>
                <div class="attachment framed">
                    <a href="<?= $block->escapeUrl($attachment) ?>" target="_blank">
                        <img src="<?= $block->escapeUrl($attachment) ?>"/>
                    </a>
                </div>
            <?php endforeach ?>
        </div>
    </div>
</section>
<?php endif ?>
<section class="admin__page-section simplereturns-rma-customer-info">
    <div class="admin__page-section-item customer-account-information">
        <div class="admin__page-section-item-title">
            <span class="title"><?= $block->escapeHtml(__('Customer Information')) ?></span>
            <div class="actions">
                <?php if ($customerUrl): ?>
                    <a href="<?= /* @noEscape */ $customerUrl ?>" target="_blank">
                        <?= $block->escapeHtml(__('Edit Customer')) ?>
                    </a>
                <?php endif ?>
            </div>
        </div>
        <div class="admin__page-section-item-content">
            <table class="admin__table-secondary customer-account-information-table">
                <tr>
                    <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                    <td>
                        <?php if ($customerUrl): ?>
                            <a href="<?= $block->escapeUrl($customerUrl) ?>" target="_blank">
                                <span><?= $block->escapeHtml($order->getCustomerName()) ?></span>
                            </a>
                        <?php else: ?>
                            <?= $block->escapeHtml($order->getCustomerName()) ?>
                        <?php endif ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Email')) ?></th>
                    <td>
                        <a href="mailto:<?= $block->escapeHtmlAttr($order->getCustomerEmail()) ?>"><?= $block->escapeHtml($order->getCustomerEmail()) ?></a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</section>
