<?php
/**
 * media.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT license, which
 * is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package     AuroraExtensions\SimpleReturns
 * @copyright   Copyright (C) 2023 Aurora Extensions <support@auroraextensions.com>
 * @license     MIT
 */

/**
 * @see AuroraExtensions\SimpleReturns\Api\Data\AttachmentInterface
 * @see AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\ViewView
 * @see Magento\Framework\View\Element\Template
 */

/** @var Template $block */
/** @var ViewView $viewModel */
$viewModel = $block->getViewModel();
?>
<?php if ($viewModel->hasAttachments()): ?>
<?php /** @var array $attachments */ ?>
<?php $attachments = $viewModel->getAttachments() ?>
<h3 class="subtitle"><?= $block->escapeHtml(__('Attachments')) ?></h3>
<div class="media">
    <div class="row">
        <span class="value attachments">
        <?php foreach ($attachments as $attachment): ?>
            <div class="attachment framed">
                <a href="<?= $block->escapeUrl($attachment) ?>" target="_blank">
                    <img src="<?= $block->escapeUrl($attachment) ?>"/>
                </a>
            </div>
        <?php endforeach ?>
        </span>
    </div>
</div>
<?php endif ?>
