<?php
/**
 * title.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License, which
 * is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       MIT License
 */

/**
 * @see AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\ViewView
 * @see Magento\Framework\View\Element\Template
 * @see Magento\Sales\Api\Data\OrderInterface
 */

/** @var Template $block */
/** @var ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var OrderInterface $order */
$order = $viewModel->getOrder();
?>
<h2><?= $block->escapeHtml(__('View RMA Details for Order #%1', $order->getRealOrderId())) ?></h2>
