<?php
/**
 * recent.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Aurora Extensions EULA,
 * which is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       Aurora Extensions EULA
 */

/**
 * @see Magento_Sales::order/recent.phtml
 */
use Magento\Framework\Data\Helper\PostHelper;
use Magento\Sales\Helper\Reorder as ReorderHelper;

/** @var AuroraExtensions\SimpleReturns\Model\ViewModel\OrdersView */
$viewModel = $block->getViewModel();

/** @var OrderInterface[] $orders */
$orders = $block->getOrders();

/** @var int $count */
$count = count($orders);
?>
<div class="block block-dashboard-orders">
    <div class="block-title order">
        <strong><?= __('Recent Orders') ?></strong>
        <?php if ($count > 0): ?>
            <a class="action view" href="<?= $block->getUrl('sales/order/history') ?>">
                <span><?= __('View All') ?></span>
            </a>
        <?php endif ?>
    </div>
    <div class="block-content">
        <?= $block->getChildHtml() ?>
        <?php if ($count > 0): ?>
            <div class="table-wrapper orders-recent">
                <table class="data table table-order-items recent" id="my-orders-table">
                    <caption class="table-caption"><?= __('Recent Orders') ?></caption>
                    <thead>
                        <tr>
                            <th class="col id" scope="col"><?= __('Order #') ?></th>
                            <th class="col date" scope="col"><?= __('Date') ?></th>
                            <th class="col shipping" scope="col"><?= __('Ship To') ?></th>
                            <th class="col total" scope="col"><?= __('Order Total') ?></th>
                            <th class="col status" scope="col"><?= __('Status') ?></th>
                            <th class="col actions" scope="col"><?= __('Actions') ?></th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($orders as $order): ?>
                            <tr>
                                <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= $order->getRealOrderId() ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= $block->formatDate($order->getCreatedAt()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $order->getShippingAddress() ? $block->escapeHtml($order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= $order->formatPrice($order->getGrandTotal()) ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $order->getStatusLabel() ?></td>
                                <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                                    <a href="<?= $block->getViewUrl($order) ?>" class="action view">
                                        <span><?= __('View Order') ?></span>
                                    </a>
                                    <?php if ($this->helper(ReorderHelper::class)->canReorder($order->getEntityId())): ?>
                                        <a class="action order" href="#" data-post="<?= $this->helper(PostHelper::class)->getPostData($block->getReorderUrl($order)) ?>">
                                            <span><?= __('Reorder') ?></span>
                                        </a>
                                    <?php endif ?>
                                    <?php if ($viewModel->isOrderPrepaidEligible($order)): ?>
                                        <a class="action print-return-label" href="<?= $viewModel->getReturnLabelUrl($order) ?>" target="_blank">
                                            <span><?= __('Print Return Label') ?></span>
                                        </a>
                                    <?php endif ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message info empty">
                <span><?= __('You have placed no orders.') ?></span>
            </div>
        <?php endif ?>
    </div>
</div>
