<?php
/**
 * customer.phtml
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the MIT License, which
 * is bundled with this package in the file LICENSE.txt.
 *
 * It is also available on the Internet at the following URL:
 * https://docs.auroraextensions.com/magento/extensions/2.x/simplereturns/LICENSE.txt
 *
 * @package       AuroraExtensions_SimpleReturns
 * @copyright     Copyright (C) 2019 Aurora Extensions <support@auroraextensions.com>
 * @license       MIT License
 */

/**
 * @see AuroraExtensions\SimpleReturns\Model\ViewModel\Rma\ViewView
 * @see Magento\Framework\View\Element\Template
 * @see Magento\Sales\Api\Data\OrderInterface
 */

/** @var Template $block */
/** @var ViewView $viewModel */
$viewModel = $block->getViewModel();

/** @var OrderInterface $order */
$order = $viewModel->getOrder();

/** @var string $customerUrl */
$customerUrl = $viewModel->getViewCustomerUrl();
?>
<section class="admin__page-section simplereturns-rma-customer-info">
    <div class="admin__page-section-item customer-account-information">
        <div class="admin__page-section-item-title">
            <span class="title"><?= $block->escapeHtml(__('Customer Information')) ?></span>
            <div class="actions">
                <?php if ($customerUrl): ?>
                    <a href="<?= /* @noEscape */ $customerUrl ?>" target="_blank">
                        <?= $block->escapeHtml(__('Edit Customer')) ?>
                    </a>
                <?php endif ?>
            </div>
        </div>
        <div class="admin__page-section-item-content">
            <table class="admin__table-secondary customer-account-information-table">
                <tr>
                    <th><?= $block->escapeHtml(__('Customer Name')) ?></th>
                    <td>
                        <?php if ($customerUrl): ?>
                            <a href="<?= $block->escapeUrl($customerUrl) ?>" target="_blank">
                                <span><?= $block->escapeHtml($order->getCustomerName()) ?></span>
                            </a>
                        <?php else: ?>
                            <?= $block->escapeHtml($order->getCustomerName()) ?>
                        <?php endif ?>
                    </td>
                </tr>
                <tr>
                    <th><?= $block->escapeHtml(__('Email')) ?></th>
                    <td>
                        <a href="mailto:<?= $block->escapeHtmlAttr($order->getCustomerEmail()) ?>"><?= $block->escapeHtml($order->getCustomerEmail()) ?></a>
                    </td>
                </tr>
            </table>
        </div>
    </div>
</section>
